name: supersonido-outlet-monitor

on:
  schedule:
  - cron: '0 8-23 * * 1-6'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-22.04  # More recent than "latest" which is 20.04
    container: python:3.10-slim  # Smaller base image with pre-installed Python

    steps:
    - uses: actions/checkout@v4  # Faster checkout version
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      if: contains(github.event.head_commit.message, 'lint')
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run scrapers in parallel
      run: |
        python scraper_supersonido.py ${{ secrets.TELEGRAM_API_KEY }} ${{ secrets.TELEGRAM_CHAT_ID }} &
        python scraper_supersonido_offers.py ${{ secrets.TELEGRAM_API_KEY }} ${{ secrets.TELEGRAM_CHAT_ID }} &
        wait  # Wait for both scrapers to finish

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y git

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: "Updated supersonido jsons"
        branch: "main"
        file_pattern: "*.json"  # Explicitly target JSON files
        commit_user_name: "Supersonido Bot"
        commit_user_email: "bot@supersonido"
